package mastr

import (
	"database/sql"
	"fmt"
	"regexp"
	"time"
)

// Meta describes which MaStR export a given mastr.db was built from and
// when the import ran. Stored in a single-row "meta" table inside the
// SQLite database itself, so any consumer of mastr.db (Go code, ad-hoc SQL,
// other tools) can tell which data snapshot they're looking at without
// needing external bookkeeping.
type Meta struct {
	// SourceFile is the original zip file name, e.g.
	// "Gesamtdatenexport_20260713_26.1.zip".
	SourceFile string

	// SourceDate is the "Stichtag"/export date encoded in the file name
	// (the date the Gesamtdatenexport was generated by the
	// Marktstammdatenregister, not the import date).
	SourceDate time.Time

	// SourceVersion is the export format/tooling version encoded in the
	// file name, e.g. "26.1".
	SourceVersion string

	// ImportedAt is when this database was (re-)built from SourceFile.
	ImportedAt time.Time
}

// sourceFileNamePattern matches the official Gesamtdatenexport naming
// scheme, e.g. "Gesamtdatenexport_20260713_26.1.zip".
var sourceFileNamePattern = regexp.MustCompile(`^Gesamtdatenexport_(\d{8})_([0-9]+(?:\.[0-9]+)*)\.zip$`)

// ParseSourceFileName extracts the export date and version encoded in a
// MaStR bulk export zip's file name. Returns an error if fileName doesn't
// match the expected "Gesamtdatenexport_YYYYMMDD_VERSION.zip" pattern.
func ParseSourceFileName(fileName string) (sourceDate time.Time, sourceVersion string, err error) {
	m := sourceFileNamePattern.FindStringSubmatch(fileName)
	if m == nil {
		return time.Time{}, "", fmt.Errorf("mastr: file name %q does not match expected pattern Gesamtdatenexport_YYYYMMDD_VERSION.zip", fileName)
	}
	sourceDate, err = time.Parse("20060102", m[1])
	if err != nil {
		return time.Time{}, "", fmt.Errorf("mastr: parsing date from file name %q: %w", fileName, err)
	}
	return sourceDate, m[2], nil
}

const createMetaTableSQL = `
CREATE TABLE IF NOT EXISTS meta (
	id             INTEGER PRIMARY KEY CHECK (id = 1),
	source_file    TEXT NOT NULL,
	source_date    TEXT NOT NULL,
	source_version TEXT NOT NULL,
	imported_at    TEXT NOT NULL
);`

// WriteMeta creates the meta table if needed and (re-)writes the single
// meta row describing the data currently imported into db. Called by the
// importer once an import has completed successfully.
func WriteMeta(db *sql.DB, m Meta) error {
	if _, err := db.Exec(createMetaTableSQL); err != nil {
		return fmt.Errorf("mastr: creating meta table: %w", err)
	}
	_, err := db.Exec(
		`INSERT INTO meta (id, source_file, source_date, source_version, imported_at)
		 VALUES (1, ?, ?, ?, ?)
		 ON CONFLICT(id) DO UPDATE SET
			source_file = excluded.source_file,
			source_date = excluded.source_date,
			source_version = excluded.source_version,
			imported_at = excluded.imported_at`,
		m.SourceFile,
		m.SourceDate.UTC().Format(time.RFC3339),
		m.SourceVersion,
		m.ImportedAt.UTC().Format(time.RFC3339),
	)
	if err != nil {
		return fmt.Errorf("mastr: writing meta row: %w", err)
	}
	return nil
}

// Meta returns the stored Meta row describing which MaStR export this
// database was built from, and when. Returns an error if the meta table
// doesn't exist yet (i.e. no successful import has ever written it).
func (s *Store) Meta() (Meta, error) {
	row := s.db.QueryRow(`SELECT source_file, source_date, source_version, imported_at FROM meta WHERE id = 1`)

	var m Meta
	var sourceDate, importedAt string
	if err := row.Scan(&m.SourceFile, &sourceDate, &m.SourceVersion, &importedAt); err != nil {
		if err == sql.ErrNoRows {
			return Meta{}, fmt.Errorf("mastr: no meta row found (database not imported yet?): %w", err)
		}
		return Meta{}, fmt.Errorf("mastr: reading meta row: %w", err)
	}
	var err error
	if m.SourceDate, err = time.Parse(time.RFC3339, sourceDate); err != nil {
		return Meta{}, fmt.Errorf("mastr: parsing stored source_date %q: %w", sourceDate, err)
	}
	if m.ImportedAt, err = time.Parse(time.RFC3339, importedAt); err != nil {
		return Meta{}, fmt.Errorf("mastr: parsing stored imported_at %q: %w", importedAt, err)
	}
	return m, nil
}
